### Importing Packages

In [5]:
import numpy as np

In [6]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)
#to better view the outputs on the screen
#suppress = True disables scientific notations
# linewidth extend the number of characters we fit in a line to 100
#precision gives values in only two digits

### Importing the Data

In [7]:
raw_data_np = np.genfromtxt("loan-data.csv", delimiter = ";", skip_header = 1, autostrip = True)
raw_data_np
#autostrip gets rid of unnecessary white spaces

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

### Checking for Incomplete Data

In [8]:
np.isnan(raw_data_np).sum()

88005

In [9]:
temp_fill = np.nanmax(raw_data_np) + 1
temp_mean = np.nanmean(raw_data_np, axis = 0)

C:\Users\Dell\AppData\Local\Temp/ipykernel_18936/1910991242.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data_np, axis = 0)


In [10]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [11]:
temp_stats = np.array([np.nanmin(raw_data_np, axis = 0),
                     temp_mean,
                     np.nanmax(raw_data_np, axis = 0)])

C:\Users\Dell\AppData\Local\Temp/ipykernel_18936/501956023.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data_np, axis = 0),
C:\Users\Dell\AppData\Local\Temp/ipykernel_18936/501956023.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis = 0)])


In [12]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

### Splitting the Dataset

In [13]:
column_strings = np.argwhere(np.isnan(temp_mean)).squeeze()
#the string columns are those whose mean is nan
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [14]:
column_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Re-importing the Dataset

In [15]:
loan_data_strings = np.genfromtxt("loan-data.csv",
                            delimiter = ";",
                            skip_header = 1,
                            autostrip = True,
                            usecols = column_strings,
                            dtype = np.str_)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [16]:
loan_data_numeric = np.genfromtxt("loan-data.csv",
                            delimiter = ";",
                            skip_header = 1,
                            autostrip = True,
                            usecols = column_numeric,
                            filling_values = temp_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### The Names of the Columns

In [17]:
header_full = np.genfromtxt("loan-data.csv",
                            delimiter = ";",
                            skip_footer = raw_data_np.shape[0],
                            autostrip = True,
                            dtype = np.str_)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [18]:
header_strings, header_numeric = header_full[column_strings], header_full[column_numeric]

In [19]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [20]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### Creating Checkpoints

In [21]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [22]:
checkpoint_test = checkpoint("checkpoint-test", header_strings, loan_data_strings)

In [23]:
checkpoint_test["header"]

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [24]:
checkpoint_test["data"]

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [25]:
np.array_equal(checkpoint_test['data'], loan_data_strings)

True

### Manipulating String Columns

In [26]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [27]:
header_strings[0] = "issue_date"

In [28]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Issue Date

In [29]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [30]:
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0], "-15" )

In [31]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [32]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [33]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                      i,
                                      loan_data_strings[:,0])
    
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [34]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [35]:
np.unique(loan_data_strings[:,1])
#can also use the size attibute to know th enumber of unique values

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [36]:
status_bad = np.array(['', 'Charged Off', 'Default',
                       'Late (31-120 days)'])

In [37]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1], status_bad),0,1)
#np.unique(loan_data_strings[:,1])
loan_data_strings[:,1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

### Term

In [38]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [39]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [40]:
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2], " months")
np.unique(loan_data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

In [41]:
header_strings[2] = "term_months"
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [42]:
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == "",
                                '60',
                                loan_data_strings[:,2])
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [43]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

### Grade and Sub Grade

In [44]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [45]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [46]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

### Fitting Sub Grade

In [47]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [48]:
#for i in loan_data_strings[:,4][1:]:
#    loan_data_strings[:,4] = np.where()

In [49]:
loan_data_strings[:,3:5]

array([['C', 'C3'],
       ['A', 'A5'],
       ['B', 'B5'],
       ...,
       ['A', 'A5'],
       ['D', 'D2'],
       ['A', 'A4']], dtype='<U69')

In [50]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                     i + '5',
                                     loan_data_strings[:,4])
np.unique(loan_data_strings[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [51]:
#loan_data_strings[:,4] = np.where(loan_data_strings[:,4] == '5', '', 
#                                 loan_data_strings[:,4])
#np.unique(loan_data_strings[:,4])

In [52]:
np.unique(loan_data_strings[:,3])[1:]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

### Removing Grade

In [58]:
loan_data_strings = np.delete(loan_data_strings, 3, axis = 1)


In [60]:
loan_data_strings[:,3]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [54]:
header_strings = np.delete(header_strings,3)

In [55]:
header_strings[3]

'sub_grade'

### Converting to Sub Grade

In [62]:
#the code below is written for sb grade but due to running this code multiple times
#sub grade has been deleted, but the code is correct

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [ ]:
np.unique(loan_data_strings[:,3])

In [ ]:
keys = list(np.unique(loan_data_strings[:3]))
values = list(range(1, npunique(loandata_strings[:,3]).shape[0]+1))
dict_sub_grade = dict(zip(keys,values))

In [ ]:
dict_sub_grade

In [ ]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3] = np.where(loan_data_string[:,3]) == i,
                                dict_sub_grade[i],
                                loan_data_strings[:,3]

In [ ]:
np.unique(loan_data_strings[:,3])

### Verification Status and URL

In [67]:
#header_strings = np.delete(header_strings,3)

In [69]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [70]:
np.unique(loan_data_strings[:,3])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [79]:
loan_data_strings[:,3] = np.where((loan_data_strings[:,3] == '') | (loan_data_strings[:,3] == 'Not Verified'), 0, 1)

In [82]:
np.unique(loan_data_strings[:,3])
#the answer should be 0 and 1 for unique values

array(['1'], dtype='<U69')

### URL

In [86]:
loan_data_strings[:,4]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [88]:
np.chararray.strip(loan_data_strings[:,4], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')


chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [90]:
loan_data_strings[:,4] = np.chararray.strip(loan_data_strings[:,4], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [92]:
loan_data_strings[:,4]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [102]:
loan_data_numeric[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [103]:
loan_data_strings[:,4].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [107]:
np.array_equal(loan_data_numeric[:,0].astype(dtype = np.int32), loan_data_strings[:,4].astype(dtype = np.int32))

True

In [109]:
loan_data_strings[:,4]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [113]:
#loan_data_strings = np.delete(loan_data_strings, 4, axis = 1)
#header_strings = np.delete(header_strings, 4)

In [118]:
loan_data_strings
header_strings

array(['issue_date', 'loan_status', 'term_months', 'verification_status'], dtype='<U19')

### State Address

In [119]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'verification_status'], dtype='<U19')

In [ ]:
header_strings[5] = "state_addresses"

In [ ]:
loan_data_strings[:,5]

In [120]:
np.unique(loan_data_strings[:,5]).size

IndexError: index 5 is out of bounds for axis 1 with size 4

In [ ]:
states_names, states_counts = np.unique(loan_data_strings[:,5], return_counts = True)
states_counts_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count

In [ ]:
states_west = np.array(['WA'...........])
states_south = np.array(['WA'...........])
states_midwest = np.array(['WA'...........])
states_east = np.array(['WA'...........])
#array is created with all region

In [ ]:
loan_data_strings[:,5] = np.where(isin(loan_data_strings[:,5], states_west), 1, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(isin(loan_data_strings[:,5], states_south), 2, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(isin(loan_data_strings[:,5], states_midwest), 3, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(isin(loan_data_strings[:,5], states_east), 4, loan_data_strings[:,5])
#when in column there are names equal to the array above it is assigned a number

### Converting to Numbers

In [122]:
loan_data_strings

array([['5', '1', '36', '1'],
       ['0', '1', '36', '1'],
       ['9', '1', '36', '1'],
       ...,
       ['6', '1', '36', '1'],
       ['4', '1', '36', '1'],
       ['12', '1', '36', '1']], dtype='<U69')

In [127]:
loan_data_strings = loan_data_strings.astype(np.int_)

In [129]:
loan_data_strings

array([[ 5,  1, 36,  1],
       [ 0,  1, 36,  1],
       [ 9,  1, 36,  1],
       ...,
       [ 6,  1, 36,  1],
       [ 4,  1, 36,  1],
       [12,  1, 36,  1]])

### Checkpoint 1: Strings

In [133]:
checkpoint_strings = checkpoint('Checkpoint-Strings', header_strings, loan_data_strings)

In [134]:
checkpoint_strings["header"]

array(['issue_date', 'loan_status', 'term_months', 'verification_status'], dtype='<U19')

In [135]:
checkpoint_strings["data"]

array([[ 5,  1, 36,  1],
       [ 0,  1, 36,  1],
       [ 9,  1, 36,  1],
       ...,
       [ 6,  1, 36,  1],
       [ 4,  1, 36,  1],
       [12,  1, 36,  1]])

In [139]:
np.array_equal(checkpoint_strings["header"], header_strings)

True

### Manipulating Numeric Columns

In [140]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [143]:
np.isnan(loan_data_numeric).sum()

0

### Substitute Filler Values

In [145]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### ID

In [147]:
temp_fill

68616520.0

In [149]:
np.isin(loan_data_numeric[:,0], temp_fill)

array([False, False, False, ..., False, False, False])

In [150]:
np.isin(loan_data_numeric[:,0],temp_fill).sum()

0

In [152]:
header_numeric


array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### Temporary Stats

In [158]:
temp_stats[:, column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

### Funded Amount

In [161]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [164]:
loan_data_numeric[:,2] = np.where((loan_data_numeric[:,2]==temp_fill),
                                 temp_stats[0,column_numeric[2]],
                                 loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

### Loaned Amount, Interest Rate, Total Payment,  Installment

In [166]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [169]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where((loan_data_numeric[:,i] == temp_fill),
                                     temp_stats[2,column_numeric[i]],
                                     loan_data_numeric[:,i])

In [171]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Currency Change

### The Exchange Rate

In [175]:
EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter = ',', autostrip = True, skip_header = 1, usecols = 3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [184]:
exchange_rate = loan_data_strings[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)
    
    exchange_rate = np.where(exchange_rate == 0,
                             np.mean(EUR_USD),
                             exchange_rate)

In [185]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [187]:
exchange_rate.shape

(10000,)

In [189]:
loan_data_numeric.shape

(10000, 6)

In [191]:
#reshape the exchange rate array
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [193]:
exchange_rate.shape

(10000, 1)

In [228]:
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))

In [216]:
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))
exchange_rate
#while running the above line the exchange rate is a 0 dimensional scalar and can not be
# concatenated therefore np.array(['exchange_rate']) should be added

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

In [229]:
loan_data_numeric


array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

### Currency Exchange: USD to EUR

In [201]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'exchange_rate'], dtype='<U19')

In [204]:
columns_dollar = np.array([1,2,4,5])

In [231]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [244]:
for i in columns_dollar:
    loan_data_numeric = np.hstack(( loan_data_numeric, np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1))))

In [247]:
loan_data_numeric.shape

(10000, 11)

### Expanding the Header

In [249]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])

In [252]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'exchange_rate', 'exchange_rate', 'exchange_rate'], dtype='<U19')

In [253]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [254]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [276]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [277]:
columns_index_order = [0, 1, 7, 2, 8, 3, 4, 9, 5, 10, 6]

In [283]:
header_numeric = header_numeric[columns_index_order]
header_numeric
#reorder the headers and rewrite

array(['id', 'loan_amnt_USD', 'total_pymnt_EUR', 'installment_EUR', 'int_rate', 'loan_amnt_EUR',
       'total_pymnt_USD', 'exchange_rate', 'funded_amnt_USD', 'installment_USD', 'funded_amnt_EUR'],
      dtype='<U19')

In [316]:
loan_data_numeric = loan_data_numeric[:,columns_index_order]
loan_data_numeric
#reorder the loan_data_numeric and then overite it with the reordered array

array([[48010226.  ,    35000.  ,    31933.3 , ...,     8624.69,       13.33,    35000.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4232.39,       28.99,    30000.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1750.04,       28.99,    15000.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     1947.47,       28.99,    10000.  ],
       [46154151.  ,    35000.  ,     8997.4 , ...,     2878.63,       16.55,    10000.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,      276.11,       28.99,    10000.  ]])

### Checkpoint 2: Numeric

In [322]:
checkpoint_numeric = checkpoint("checkpoint-numeric", header_numeric, loan_data_numeric)
checkpoint_numeric['header'], checkpoint_numeric['data']

TypeError: 'NpzFile' object is not callable

### Creating the Complete Dataset

In [326]:
loan_data_strings.shape

(10000, 4)

In [328]:
loan_data_numeric.shape

(10000, 11)

In [334]:
loan_data = np.hstack((loan_data_numeric, loan_data_strings))

In [338]:
np.isnan(loan_data).sum()

0

In [341]:
header_full = np.concatenate((header_numeric, header_strings))

### Sorting the New Dataset

In [351]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [352]:
loan_data

array([[  373332.  ,     9950.  ,      908.35, ...,        1.  ,       36.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,        1.  ,       60.  ,        1.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,        1.  ,       36.  ,        1.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        1.  ,       36.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,        1.  ,       36.  ,        1.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        1.  ,       36.  ,        1.  ]])

In [354]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

### Storing the New Dataset

In [357]:
loan_data = np.vstack((header_full, loan_data))

In [359]:
np.savetxt("loan-data-preprocessed.csv",
              loan_data,
              fmt = "%s",
          delimiter = ',')